# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webmonitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(max_length=10)),
                ('companyDescr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('minFlag', models.CharField(default='N', max_length=1)),
                ('maxFlag', models.CharField(default='N', max_length=1)),
                ('avgFlag', models.CharField(default='N', max_length=1)),
                ('trendFlag', models.CharField(default='N', max_length=1)),
                ('fechaFinalFijaFlag', models.CharField(default='N', max_length=1)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('horaFinal', models.TimeField(blank=True, default='23:59', null=True)),
                ('diasComputablesFechaFinal', models.CharField(blank=True, max_length=4, null=True)),
                ('fechaInicialFijaFlag', models.CharField(default='N', max_length=1)),
                ('fechaInicial', models.DateField(blank=True, null=True)),
                ('horaInicial', models.TimeField(blank=True, default='00:01', null=True)),
                ('diasComputablesFechaInicial', models.CharField(blank=True, max_length=4, null=True)),
                ('fechaActual', models.CharField(default='N', max_length=1)),
                ('semanaAnterior', models.CharField(default='N', max_length=1)),
                ('semanaActual', models.CharField(default='N', max_length=1)),
                ('mesAnterior', models.CharField(default='N', max_length=1)),
                ('mesActual', models.CharField(default='N', max_length=1)),
                ('widgetSize', models.CharField(blank=True, max_length=10, null=True)),
                ('monitorFlag', models.CharField(default='N', max_length=1, null=True)),
                ('hour', models.CharField(default='N', max_length=1, null=True)),
                ('day', models.CharField(default='N', max_length=1, null=True)),
                ('week', models.CharField(default='N', max_length=1, null=True)),
                ('month', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomReportMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.CustomReport')),
            ],
        ),
        migrations.CreateModel(
            name='CustomReportVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=30)),
                ('customReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.CustomReport')),
            ],
        ),
        migrations.CreateModel(
            name='CustomReportWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.CustomReport')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineId', models.CharField(max_length=10, null=True)),
                ('machineDescr', models.CharField(max_length=30, null=True)),
                ('machineAlias', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDownTimeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10)),
                ('reasonDescr', models.CharField(max_length=30)),
                ('ocurrences', models.IntegerField()),
                ('duration', models.FloatField()),
                ('durationFormated', models.CharField(max_length=12)),
                ('avgDuration', models.FloatField()),
                ('avgDurationFormated', models.CharField(max_length=12)),
                ('intervalPorcentualValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineDownTimeReasonInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineGroupId', models.CharField(max_length=10)),
                ('machineGroupDescr', models.CharField(max_length=30)),
                ('machineGroupAlias', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineHistorialEventsRollOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(default=webmonitor.models.one_day_hence)),
                ('toDate', models.DateField(default=django.utils.timezone.now)),
                ('plantId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MachineHistoricalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('startDttm', models.DateTimeField()),
                ('endDttm', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('reason', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MachineHistoricalEventInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ManyToManyField(to='webmonitor.Machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantId', models.CharField(max_length=10, null=True)),
                ('plantDescr', models.CharField(max_length=30, null=True)),
                ('endPointUrl', models.URLField(null=True)),
                ('plantAlias', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonId', models.CharField(max_length=10)),
                ('reasonDescr', models.CharField(max_length=30)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportId', models.CharField(max_length=10)),
                ('reportDescr', models.CharField(max_length=50)),
                ('reportBlockName', models.CharField(max_length=50)),
                ('reportFunctionName', models.CharField(max_length=50)),
                ('maxDaysWindow', models.IntegerField(default=0)),
                ('uriIcon', models.CharField(blank=True, max_length=100, null=True)),
                ('tooltipDecr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': (('view_report_machine_status', 'View report machine status'), ('view_report_downtime_reasons', 'View report downtime reasons'), ('view_report_production_rollup', 'View report production rollup'), ('view_report_status_rollup', 'View report status rollup'), ('view_report_var_trend_rollup', 'View report var. trend rollup')),
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=10)),
                ('categoryDescr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.ManyToManyField(to='webmonitor.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableId', models.CharField(max_length=10, null=True)),
                ('variableDescr', models.CharField(max_length=30, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftId', models.CharField(max_length=10)),
                ('shiftDescr', models.CharField(max_length=30)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.CharField(max_length=10)),
                ('siteDescr', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Company')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.ReportCategory'),
        ),
        migrations.AddField(
            model_name='plant',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Site'),
        ),
        migrations.AddField(
            model_name='machinehistoricalevent',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.MachineHistoricalEventInterval'),
        ),
        migrations.AddField(
            model_name='machinegroup',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Plant'),
        ),
        migrations.AddField(
            model_name='machinedowntimereason',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.MachineHistoricalEventInterval'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machineGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.MachineGroup'),
        ),
        migrations.AddField(
            model_name='laborday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Shift'),
        ),
        migrations.AddField(
            model_name='customreportwidget',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Report'),
        ),
        migrations.AddField(
            model_name='customreportmachine',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Machine'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Machine'),
        ),
    ]
