# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftId', models.CharField(max_length=10)),
                ('shiftDescr', models.CharField(max_length=30)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Plant')),
            ],
        ),
        migrations.AddField(
            model_name='laborday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webmonitor.Shift'),
        ),
    ]
