# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborday',
            name='testField',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
