# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0002_auto_20170926_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='customreport',
            name='day',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customreport',
            name='horaFinal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customreport',
            name='horaInicial',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customreport',
            name='hour',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customreport',
            name='month',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customreport',
            name='week',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
    ]
