# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0004_auto_20170927_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machineAlias',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
