# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0005_machine_machinealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantAlias',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
