# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmonitor', '0005_machineclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertempdata',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='usertempdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserTempData',
        ),
    ]
